### ISSUE TITLE
Compliments 💰 

### ISSUE THREAD

**Issue by joe-dev-public** [fac24/ecnmy#55]
- Nice to see some custom colours in the ``tailwind.config.js``
- Nice to see some data scraping scripts 😎
- Nested dynamic routes 👍 
- Looking forward to seeing a demo, feels like there's a lot going on/a lot of background work which isn't necessarily visible yet :)

**Comment by mariaalouisaa** [comment]
- Nice to read through this complex repo!
- Second what joe said re: scraping and dynamic paths
- Good UX, nice graphs
- Can't wait to see your presentation
