### ISSUE TITLE
👀 interesting...

### ISSUE THREAD

**Issue by mariaalouisaa** [fac24/ecnmy#57]
See this a bit on your dynamic pages - is this a hacky way around / a weird next.js thing. I'm very intrigued!

https://github.com/fac24/ecnmy/blob/01c5ad6d4b942f9adbda1aa332d6bb0484cb5015/pages/%5Blocation%5D/topic/%5Btopic%5D.js#L14

**Comment by Glombort** [comment]
Lool yes we're still trying to wrap our heads around it too, and work out the non hacky way to fix it
